# Generated by Django 2.2 on 2022-07-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hypervisortabledb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypervisorIP', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('operatingSystem', models.CharField(max_length=100)),
                ('ipAddress', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
