# Generated by Django 2.2 on 2022-07-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypervisortabledb',
            name='ipAddress',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
