# Generated by Django 2.2 on 2022-08-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVMpatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypervisorIP', models.CharField(max_length=16)),
                ('script', models.FileField(upload_to='scriptdocs/')),
            ],
        ),
    ]
