# Generated by Django 2.2 on 2022-08-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patchpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadVMpatch',
            new_name='UploadVMpatchdb',
        ),
    ]
