# Generated by Django 2.2 on 2022-08-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchpanel', '0002_auto_20220803_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvmpatchdb',
            name='script',
            field=models.FileField(null=True, upload_to='scriptdocs/'),
        ),
    ]
