# Generated by Django 2.2 on 2022-08-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchpanel', '0004_auto_20220803_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvmpatchdb',
            name='script',
            field=models.FileField(upload_to=''),
        ),
    ]
