# Generated by Django 2.2 on 2022-08-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patchpanel', '0006_auto_20220803_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvmpatchdb',
            name='hypervisorIP',
        ),
    ]
